language: c

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
  apt:
    packages:
      - cmake3 # 3.5.1
      - g++ # 4.8.2
      - libgomp1 # 4.8.4
      - libfftw3-dev # version 3.3.3
      - mpi-default-dev # version 4.8.4
      - libtiff5-dev # version 5 ?
      - libboost-all-dev # version 1.54
      - libeigen3-dev # version 3.2.0
      - llvm # version 3.4
      # - libcfitsio3-dev # version 3.34
      # - libccfits-dev # version 2.4
      # - libyaml-cpp-dev # version 0.5.1

# libtiff is version 5 in Trusty

# env:
#     global:
#         - SETUP_CMD='test'
#         - TEST_CMD='py.test test_env.py'
#         - PYTHON_VERSION=3.6

#     matrix:
#         - SETUP_CMD='egg_info' TEST_CMD='python --version'

matrix:
  # Don't wait for allowed failures - do we really need this? TODO
  fast_finish: true

  include:
    - os: osx
      #language: generic
      env: TITLE="All dependencies"
      
    - os: linux
      dist: trusty
      sudo: required
      env: TITLE="All dependencies" DEBUG=True LDFLAGS='-lpthread'
      #language: generic

    # - os: linux # no dependencies installed
  #   - os: linux #Documentation? To push to gh-pages
  #     env: PYTHON_VERSION=3.4 PYTEST_VERSION=3.1 PIP_FALLBACK=false
      
  # allow_failures:
  #   - os: linux #Benchmark
  #     env: PYTHON_VERSION=3.4 PYTEST_VERSION=3.1 PIP_FALLBACK=false

before_install:
  - echo "==================== ${TITLE} ====================="
  # Install stuff specifically for MacOS
  #- if [ $TRAVIS_OS_NAME = osx ]; then brew update; rm '/usr/local/include/c++'; brew install gcc; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then source .ci/setup_linux.sh; fi


install:

before_script:

script:
  - pwd
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -Ddompi=OFF -Dexamples=OFF -Dopenmp=OFF
  - make VERBOSE=1
  - ctest -T test --output-on-failure -V

after_success:

